package entity;
// Generated Nov 7, 2017 10:06:23 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserAcc generated by hbm2java
 */
@Entity
@Table(name = "LIST_MCC", schema = "CCPS"
)
public class ListMcc implements java.io.Serializable {

    private String mccCode;
    private String merchantType;

    public ListMcc() {
    }

    @Id
    @Column(name = "MCC_CODE", unique = true, nullable = false, length = 8)
    public String getMccCode() {
        return mccCode;
    }

    public void setMccCode(String mccCode) {
        this.mccCode = mccCode;
    }

    @Column(name = "MERCHANT_TYPE", length = 500)
    public String getMerchantType() {
        return merchantType;
    }

    public void setMerchantType(String merchantType) {
        this.merchantType = merchantType;
    }

}
