package entity;
// Generated Oct 30, 2017 8:31:15 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TtDvcnt generated by hbm2java
 */
@Entity
@Table(name = "TT_DVCNT_LIVE", schema = "CCPS"
)
public class TtDvcntLive implements java.io.Serializable {

    private String maDvcnt;
    private String tenDvcntVn;
    private String tenDvcntEn;
    private String diachiDvcnt;
    private String sdtDvcnt;
    private String gpdkkdso;
    private Integer gpdkkdNgaycap;
    private String gpdkkdNoicap;
    private String gpdkkdTennguoidaidien;
    private String gpdkkdChucvu;
    private String gpdkkdCmnd;
    private Integer gpdkkdNgaycapCmnd;
    private String gpdkkdNoicapCmnd;
    private String masothue;
    private String tennguoiKyhopdong;
    private String chucvuHopdong;
    private String cmndHopdong;
    private Integer ngaycapCmndHopdong;
    private String noicapCmndHopdong;
    private String soUyquyen;
    private Integer ngayUyquyen;
    private String nganhangHoptac;
    private Byte loaihinhDvcnt;
    private String nganhnghekd;
    private Long doanhsothanhtoandukien;
    private Character xeploai;
    private Byte landk;
    private Integer slpos;
    private String dongmayDexuat;
    private String phiGhinoscb;
    private String phiGhinoLienminh;
    private String phiVisa;
    private String phiMastercard;
    private String phiJcb;
    private String phiCup;
    private String phiDiscover;
    private String tenThekhac;
    private String phiThekhac;
    private String loaitien;
    private Long tienkyquyMoto;
    private String user1Cn;
    private Long user1CnNgaynhap;
    private String user2Cn;
    private Long user2CnDate;
    private String user2CnNote;
    private String user1Ptdbh;
    private Long user1PtdbhDate;
    private String user1PtdbhNote;
    private String user2Ptdbh;
    private Long user2PtdbhDate;
    private String user2PtdbhNote;
    private String user1Pkhdn;
    private Long user1PkhdnDate;
    private String user1PkhdnNote;
    private String user2Pkhdn;
    private Long user2PkhdnDate;
    private String user2PkhdnNote;
    private String user1Ptnt;
    private Long user1PtntDate;
    private String user1PtntNote;
    private String user2Ptnt;
    private Long user2PtntDate;
    private String user2PtntNote;
    private String cnQuanly;
    private Byte statusDuyet;
    private Byte statusDvcnt;
    private Long hanmucVnd;
    private Long hanmucUsd;
    private Byte soluonglapthem;
    private String fileUpload;
    private String fileUpload2;
    private String edit1;
    private String edit2;
    private String edit3;
    private String edit4;
    private String fileUpload3;
    private String fileUploadTamkhoa;
    private String fileUploadkhoa;
    private String logUser;
    private Byte bbbglapthem;
    private Byte bbbgthemmoi;
    private Byte bbbgkhoa;
    private Byte bbbgtamkhoa;
    private String tenFileBbbg;
    private String directName;
    private String indirectName;
    private String directCode;
    private String indirectCode;
    private String directJobtitleCode;
    private String indirectJobtitleCode;
    private String directJobtitleName;
    private String indirectJobtitleName;
    private String directBranchName;
    private String indirectBranchName;
    private Integer thoiGianLapDat;
    private String loaiKhachHang;
    private String fileMapping;
    private String loaiDoanhNghiep;

    public TtDvcntLive() {
    }

    public TtDvcntLive(String maDvcnt) {
        this.maDvcnt = maDvcnt;
    }

    public TtDvcntLive(String maDvcnt, String tenDvcntVn, String tenDvcntEn,
            String diachiDvcnt, String sdtDvcnt, String gpdkkdso, Integer gpdkkdNgaycap,
            String gpdkkdNoicap, String gpdkkdTennguoidaidien, String gpdkkdChucvu,
            String gpdkkdCmnd, Integer gpdkkdNgaycapCmnd, String gpdkkdNoicapCmnd,
            String masothue, String tennguoiKyhopdong, String chucvuHopdong,
            String cmndHopdong, Integer ngaycapCmndHopdong, String noicapCmndHopdong,
            String soUyquyen, Integer ngayUyquyen, String nganhangHoptac,
            Byte loaihinhDvcnt, String nganhnghekd, Long doanhsothanhtoandukien,
            Character xeploai, Byte landk, Integer slpos, String dongmayDexuat,
            String phiGhinoscb, String phiGhinoLienminh, String phiVisa,
            String phiMastercard, String phiJcb, String phiCup, String phiDiscover,
            String tenThekhac, String phiThekhac, String loaitien, Long tienkyquyMoto,
            String user1Cn, Long user1CnNgaynhap, String user2Cn, Long user2CnDate,
            String user2CnNote, String user1Ptdbh, Long user1PtdbhDate, String user1PtdbhNote,
            String user2Ptdbh, Long user2PtdbhDate, String user2PtdbhNote, String user1Pkhdn,
            Long user1PkhdnDate, String user1PkhdnNote, String user2Pkhdn, Long user2PkhdnDate,
            String user2PkhdnNote, String user1Ptnt, Long user1PtntDate, String user1PtntNote,
            String user2Ptnt, Long user2PtntDate, String user2PtntNote, String cnQuanly,
            Byte statusDuyet, Byte statusDvcnt, Long hanmucVnd, Long hanmucUsd,
            Byte soluonglapthem, String fileUpload, String fileUpload2, String edit1,
            String edit2, String edit3, String edit4, String fileUpload3, String fileUploadTamkhoa,
            String fileUploadkhoa, String logUser, Byte bbbglapthem, Byte bbbgthemmoi,
            Byte bbbgkhoa, Byte bbbgtamkhoa, String tenFileBbbg, Integer thoiGianLapDat, String loaiKhachHang) {
        this.maDvcnt = maDvcnt;
        this.tenDvcntVn = tenDvcntVn;
        this.tenDvcntEn = tenDvcntEn;
        this.diachiDvcnt = diachiDvcnt;
        this.sdtDvcnt = sdtDvcnt;
        this.gpdkkdso = gpdkkdso;
        this.gpdkkdNgaycap = gpdkkdNgaycap;
        this.gpdkkdNoicap = gpdkkdNoicap;
        this.gpdkkdTennguoidaidien = gpdkkdTennguoidaidien;
        this.gpdkkdChucvu = gpdkkdChucvu;
        this.gpdkkdCmnd = gpdkkdCmnd;
        this.gpdkkdNgaycapCmnd = gpdkkdNgaycapCmnd;
        this.gpdkkdNoicapCmnd = gpdkkdNoicapCmnd;
        this.masothue = masothue;
        this.tennguoiKyhopdong = tennguoiKyhopdong;
        this.chucvuHopdong = chucvuHopdong;
        this.cmndHopdong = cmndHopdong;
        this.ngaycapCmndHopdong = ngaycapCmndHopdong;
        this.noicapCmndHopdong = noicapCmndHopdong;
        this.soUyquyen = soUyquyen;
        this.ngayUyquyen = ngayUyquyen;
        this.nganhangHoptac = nganhangHoptac;
        this.loaihinhDvcnt = loaihinhDvcnt;
        this.nganhnghekd = nganhnghekd;
        this.doanhsothanhtoandukien = doanhsothanhtoandukien;
        this.xeploai = xeploai;
        this.landk = landk;
        this.slpos = slpos;
        this.dongmayDexuat = dongmayDexuat;
        this.phiGhinoscb = phiGhinoscb;
        this.phiGhinoLienminh = phiGhinoLienminh;
        this.phiVisa = phiVisa;
        this.phiMastercard = phiMastercard;
        this.phiJcb = phiJcb;
        this.phiCup = phiCup;
        this.phiDiscover = phiDiscover;
        this.tenThekhac = tenThekhac;
        this.phiThekhac = phiThekhac;
        this.loaitien = loaitien;
        this.tienkyquyMoto = tienkyquyMoto;
        this.user1Cn = user1Cn;
        this.user1CnNgaynhap = user1CnNgaynhap;
        this.user2Cn = user2Cn;
        this.user2CnDate = user2CnDate;
        this.user2CnNote = user2CnNote;
        this.user1Ptdbh = user1Ptdbh;
        this.user1PtdbhDate = user1PtdbhDate;
        this.user1PtdbhNote = user1PtdbhNote;
        this.user2Ptdbh = user2Ptdbh;
        this.user2PtdbhDate = user2PtdbhDate;
        this.user2PtdbhNote = user2PtdbhNote;
        this.user1Pkhdn = user1Pkhdn;
        this.user1PkhdnDate = user1PkhdnDate;
        this.user1PkhdnNote = user1PkhdnNote;
        this.user2Pkhdn = user2Pkhdn;
        this.user2PkhdnDate = user2PkhdnDate;
        this.user2PkhdnNote = user2PkhdnNote;
        this.user1Ptnt = user1Ptnt;
        this.user1PtntDate = user1PtntDate;
        this.user1PtntNote = user1PtntNote;
        this.user2Ptnt = user2Ptnt;
        this.user2PtntDate = user2PtntDate;
        this.user2PtntNote = user2PtntNote;
        this.cnQuanly = cnQuanly;
        this.statusDuyet = statusDuyet;
        this.statusDvcnt = statusDvcnt;
        this.hanmucUsd = hanmucUsd;
        this.hanmucVnd = hanmucVnd;
        this.soluonglapthem = soluonglapthem;
        this.fileUpload = fileUpload;
        this.fileUpload2 = fileUpload2;
        this.edit1 = edit1;
        this.edit2 = edit2;
        this.edit3 = edit3;
        this.edit4 = edit4;
        this.fileUpload3 = fileUpload3;
        this.fileUploadTamkhoa = fileUploadTamkhoa;
        this.fileUploadkhoa = fileUploadkhoa;
        this.logUser = logUser;
        this.bbbglapthem = bbbglapthem;
        this.bbbgthemmoi = bbbgthemmoi;
        this.bbbgkhoa = bbbgkhoa;
        this.bbbgtamkhoa = bbbgtamkhoa;
        this.tenFileBbbg = tenFileBbbg;
        this.thoiGianLapDat = thoiGianLapDat;
        this.loaiKhachHang = loaiKhachHang;
        this.loaiDoanhNghiep = loaiDoanhNghiep;
    }

    @Id

    @Column(name = "MA_DVCNT", unique = true, nullable = false, length = 50)
    public String getMaDvcnt() {
        return this.maDvcnt;
    }

    public void setMaDvcnt(String maDvcnt) {
        this.maDvcnt = maDvcnt;
    }

    @Column(name = "TEN_DVCNT_VN", length = 100)
    public String getTenDvcntVn() {
        return this.tenDvcntVn;
    }

    public void setTenDvcntVn(String tenDvcntVn) {
        this.tenDvcntVn = tenDvcntVn;
    }

    @Column(name = "TEN_DVCNT_EN", length = 100)
    public String getTenDvcntEn() {
        return this.tenDvcntEn;
    }

    public void setTenDvcntEn(String tenDvcntEn) {
        this.tenDvcntEn = tenDvcntEn;
    }

    @Column(name = "DIACHI_DVCNT", length = 100)
    public String getDiachiDvcnt() {
        return this.diachiDvcnt;
    }

    public void setDiachiDvcnt(String diachiDvcnt) {
        this.diachiDvcnt = diachiDvcnt;
    }

    @Column(name = "SDT_DVCNT", length = 30)
    public String getSdtDvcnt() {
        return this.sdtDvcnt;
    }

    public void setSdtDvcnt(String sdtDvcnt) {
        this.sdtDvcnt = sdtDvcnt;
    }

    @Column(name = "GPDKKDSO", length = 50)
    public String getGpdkkdso() {
        return this.gpdkkdso;
    }

    public void setGpdkkdso(String gpdkkdso) {
        this.gpdkkdso = gpdkkdso;
    }

    @Column(name = "GPDKKD_NGAYCAP", precision = 8, scale = 0)
    public Integer getGpdkkdNgaycap() {
        return this.gpdkkdNgaycap;
    }

    public void setGpdkkdNgaycap(Integer gpdkkdNgaycap) {
        this.gpdkkdNgaycap = gpdkkdNgaycap;
    }

    @Column(name = "GPDKKD_NOICAP", length = 50)
    public String getGpdkkdNoicap() {
        return this.gpdkkdNoicap;
    }

    public void setGpdkkdNoicap(String gpdkkdNoicap) {
        this.gpdkkdNoicap = gpdkkdNoicap;
    }

    @Column(name = "GPDKKD_TENNGUOIDAIDIEN", length = 50)
    public String getGpdkkdTennguoidaidien() {
        return this.gpdkkdTennguoidaidien;
    }

    public void setGpdkkdTennguoidaidien(String gpdkkdTennguoidaidien) {
        this.gpdkkdTennguoidaidien = gpdkkdTennguoidaidien;
    }

    @Column(name = "GPDKKD_CHUCVU", length = 20)
    public String getGpdkkdChucvu() {
        return this.gpdkkdChucvu;
    }

    public void setGpdkkdChucvu(String gpdkkdChucvu) {
        this.gpdkkdChucvu = gpdkkdChucvu;
    }

    @Column(name = "GPDKKD_CMND", length = 20)
    public String getGpdkkdCmnd() {
        return this.gpdkkdCmnd;
    }

    public void setGpdkkdCmnd(String gpdkkdCmnd) {
        this.gpdkkdCmnd = gpdkkdCmnd;
    }

    @Column(name = "GPDKKD_NGAYCAP_CMND", precision = 8, scale = 0)
    public Integer getGpdkkdNgaycapCmnd() {
        return this.gpdkkdNgaycapCmnd;
    }

    public void setGpdkkdNgaycapCmnd(Integer gpdkkdNgaycapCmnd) {
        this.gpdkkdNgaycapCmnd = gpdkkdNgaycapCmnd;
    }

    @Column(name = "GPDKKD_NOICAP_CMND", length = 50)
    public String getGpdkkdNoicapCmnd() {
        return this.gpdkkdNoicapCmnd;
    }

    public void setGpdkkdNoicapCmnd(String gpdkkdNoicapCmnd) {
        this.gpdkkdNoicapCmnd = gpdkkdNoicapCmnd;
    }

    @Column(name = "MASOTHUE", length = 20)
    public String getMasothue() {
        return this.masothue;
    }

    public void setMasothue(String masothue) {
        this.masothue = masothue;
    }

    @Column(name = "TENNGUOI_KYHOPDONG", length = 50)
    public String getTennguoiKyhopdong() {
        return this.tennguoiKyhopdong;
    }

    public void setTennguoiKyhopdong(String tennguoiKyhopdong) {
        this.tennguoiKyhopdong = tennguoiKyhopdong;
    }

    @Column(name = "CHUCVU_HOPDONG", length = 20)
    public String getChucvuHopdong() {
        return this.chucvuHopdong;
    }

    public void setChucvuHopdong(String chucvuHopdong) {
        this.chucvuHopdong = chucvuHopdong;
    }

    @Column(name = "CMND_HOPDONG", length = 20)
    public String getCmndHopdong() {
        return this.cmndHopdong;
    }

    public void setCmndHopdong(String cmndHopdong) {
        this.cmndHopdong = cmndHopdong;
    }

    @Column(name = "NGAYCAP_CMND_HOPDONG", precision = 8, scale = 0)
    public Integer getNgaycapCmndHopdong() {
        return this.ngaycapCmndHopdong;
    }

    public void setNgaycapCmndHopdong(Integer ngaycapCmndHopdong) {
        this.ngaycapCmndHopdong = ngaycapCmndHopdong;
    }

    @Column(name = "NOICAP_CMND_HOPDONG", length = 50)
    public String getNoicapCmndHopdong() {
        return this.noicapCmndHopdong;
    }

    public void setNoicapCmndHopdong(String noicapCmndHopdong) {
        this.noicapCmndHopdong = noicapCmndHopdong;
    }

    @Column(name = "SO_UYQUYEN", length = 20)
    public String getSoUyquyen() {
        return this.soUyquyen;
    }

    public void setSoUyquyen(String soUyquyen) {
        this.soUyquyen = soUyquyen;
    }

    @Column(name = "NGAY_UYQUYEN", precision = 8, scale = 0)
    public Integer getNgayUyquyen() {
        return this.ngayUyquyen;
    }

    public void setNgayUyquyen(Integer ngayUyquyen) {
        this.ngayUyquyen = ngayUyquyen;
    }

    @Column(name = "NGANHANG_HOPTAC", length = 50)
    public String getNganhangHoptac() {
        return this.nganhangHoptac;
    }

    public void setNganhangHoptac(String nganhangHoptac) {
        this.nganhangHoptac = nganhangHoptac;
    }

    @Column(name = "LOAIHINH_DVCNT", precision = 2, scale = 0)
    public Byte getLoaihinhDvcnt() {
        return this.loaihinhDvcnt;
    }

    public void setLoaihinhDvcnt(Byte loaihinhDvcnt) {
        this.loaihinhDvcnt = loaihinhDvcnt;
    }

    @Column(name = "NGANHNGHEKD", length = 80)
    public String getNganhnghekd() {
        return this.nganhnghekd;
    }

    public void setNganhnghekd(String nganhnghekd) {
        this.nganhnghekd = nganhnghekd;
    }

    @Column(name = "DOANHSOTHANHTOANDUKIEN", precision = 12, scale = 0)
    public Long getDoanhsothanhtoandukien() {
        return this.doanhsothanhtoandukien;
    }

    public void setDoanhsothanhtoandukien(Long doanhsothanhtoandukien) {
        this.doanhsothanhtoandukien = doanhsothanhtoandukien;
    }

    @Column(name = "XEPLOAI", length = 1)
    public Character getXeploai() {
        return this.xeploai;
    }

    public void setXeploai(Character xeploai) {
        this.xeploai = xeploai;
    }

    @Column(name = "LANDK", precision = 2, scale = 0)
    public Byte getLandk() {
        return this.landk;
    }

    public void setLandk(Byte landk) {
        this.landk = landk;
    }

    @Column(name = "SLPOS", precision = 5, scale = 0)
    public Integer getSlpos() {
        return this.slpos;
    }

    public void setSlpos(Integer slpos) {
        this.slpos = slpos;
    }

    @Column(name = "DONGMAY_DEXUAT", length = 80)
    public String getDongmayDexuat() {
        return this.dongmayDexuat;
    }

    public void setDongmayDexuat(String dongmayDexuat) {
        this.dongmayDexuat = dongmayDexuat;
    }

    @Column(name = "PHI_GHINOSCB", length = 22)
    public String getPhiGhinoscb() {
        return this.phiGhinoscb;
    }

    public void setPhiGhinoscb(String phiGhinoscb) {
        this.phiGhinoscb = phiGhinoscb;
    }

    @Column(name = "PHI_GHINO_LIENMINH", length = 22)
    public String getPhiGhinoLienminh() {
        return this.phiGhinoLienminh;
    }

    public void setPhiGhinoLienminh(String phiGhinoLienminh) {
        this.phiGhinoLienminh = phiGhinoLienminh;
    }

    @Column(name = "PHI_VISA", length = 22)
    public String getPhiVisa() {
        return this.phiVisa;
    }

    public void setPhiVisa(String phiVisa) {
        this.phiVisa = phiVisa;
    }

    @Column(name = "PHI_MASTERCARD", length = 22)
    public String getPhiMastercard() {
        return this.phiMastercard;
    }

    public void setPhiMastercard(String phiMastercard) {
        this.phiMastercard = phiMastercard;
    }

    @Column(name = "PHI_JCB", length = 22)
    public String getPhiJcb() {
        return this.phiJcb;
    }

    public void setPhiJcb(String phiJcb) {
        this.phiJcb = phiJcb;
    }

    @Column(name = "PHI_CUP", length = 22)
    public String getPhiCup() {
        return this.phiCup;
    }

    public void setPhiCup(String phiCup) {
        this.phiCup = phiCup;
    }

    @Column(name = "PHI_DISCOVER", length = 22)
    public String getPhiDiscover() {
        return this.phiDiscover;
    }

    public void setPhiDiscover(String phiDiscover) {
        this.phiDiscover = phiDiscover;
    }

    @Column(name = "TEN_THEKHAC", length = 50)
    public String getTenThekhac() {
        return this.tenThekhac;
    }

    public void setTenThekhac(String tenThekhac) {
        this.tenThekhac = tenThekhac;
    }

    @Column(name = "PHI_THEKHAC", length = 22)
    public String getPhiThekhac() {
        return this.phiThekhac;
    }

    public void setPhiThekhac(String phiThekhac) {
        this.phiThekhac = phiThekhac;
    }

    @Column(name = "LOAITIEN", length = 10)
    public String getLoaitien() {
        return this.loaitien;
    }

    public void setLoaitien(String loaitien) {
        this.loaitien = loaitien;
    }

    @Column(name = "TIENKYQUY_MOTO", precision = 10, scale = 0)
    public Long getTienkyquyMoto() {
        return this.tienkyquyMoto;
    }

    public void setTienkyquyMoto(Long tienkyquyMoto) {
        this.tienkyquyMoto = tienkyquyMoto;
    }

    @Column(name = "USER1_CN", length = 10)
    public String getUser1Cn() {
        return this.user1Cn;
    }

    public void setUser1Cn(String user1Cn) {
        this.user1Cn = user1Cn;
    }

    @Column(name = "USER1_CN_NGAYNHAP", precision = 17, scale = 0)
    public Long getUser1CnNgaynhap() {
        return this.user1CnNgaynhap;
    }

    public void setUser1CnNgaynhap(Long user1CnNgaynhap) {
        this.user1CnNgaynhap = user1CnNgaynhap;
    }

    @Column(name = "USER2_CN", length = 10)
    public String getUser2Cn() {
        return this.user2Cn;
    }

    public void setUser2Cn(String user2Cn) {
        this.user2Cn = user2Cn;
    }

    @Column(name = "USER2_CN_DATE", precision = 17, scale = 0)
    public Long getUser2CnDate() {
        return this.user2CnDate;
    }

    public void setUser2CnDate(Long user2CnDate) {
        this.user2CnDate = user2CnDate;
    }

    @Column(name = "USER2_CN_NOTE", length = 250)
    public String getUser2CnNote() {
        return this.user2CnNote;
    }

    public void setUser2CnNote(String user2CnNote) {
        this.user2CnNote = user2CnNote;
    }

    @Column(name = "USER1_PTDBH", length = 10)
    public String getUser1Ptdbh() {
        return this.user1Ptdbh;
    }

    public void setUser1Ptdbh(String user1Ptdbh) {
        this.user1Ptdbh = user1Ptdbh;
    }

    @Column(name = "USER1_PTDBH_DATE", precision = 17, scale = 0)
    public Long getUser1PtdbhDate() {
        return this.user1PtdbhDate;
    }

    public void setUser1PtdbhDate(Long user1PtdbhDate) {
        this.user1PtdbhDate = user1PtdbhDate;
    }

    @Column(name = "USER1_PTDBH_NOTE", length = 250)
    public String getUser1PtdbhNote() {
        return this.user1PtdbhNote;
    }

    public void setUser1PtdbhNote(String user1PtdbhNote) {
        this.user1PtdbhNote = user1PtdbhNote;
    }

    @Column(name = "USER2_PTDBH", length = 10)
    public String getUser2Ptdbh() {
        return this.user2Ptdbh;
    }

    public void setUser2Ptdbh(String user2Ptdbh) {
        this.user2Ptdbh = user2Ptdbh;
    }

    @Column(name = "USER2_PTDBH_DATE", precision = 17, scale = 0)
    public Long getUser2PtdbhDate() {
        return this.user2PtdbhDate;
    }

    public void setUser2PtdbhDate(Long user2PtdbhDate) {
        this.user2PtdbhDate = user2PtdbhDate;
    }

    @Column(name = "USER2_PTDBH_NOTE", length = 250)
    public String getUser2PtdbhNote() {
        return this.user2PtdbhNote;
    }

    public void setUser2PtdbhNote(String user2PtdbhNote) {
        this.user2PtdbhNote = user2PtdbhNote;
    }

    @Column(name = "USER1_PKHDN", length = 10)
    public String getUser1Pkhdn() {
        return this.user1Pkhdn;
    }

    public void setUser1Pkhdn(String user1Pkhdn) {
        this.user1Pkhdn = user1Pkhdn;
    }

    @Column(name = "USER1_PKHDN_DATE", precision = 17, scale = 0)
    public Long getUser1PkhdnDate() {
        return this.user1PkhdnDate;
    }

    public void setUser1PkhdnDate(Long user1PkhdnDate) {
        this.user1PkhdnDate = user1PkhdnDate;
    }

    @Column(name = "USER1_PKHDN_NOTE", length = 250)
    public String getUser1PkhdnNote() {
        return this.user1PkhdnNote;
    }

    public void setUser1PkhdnNote(String user1PkhdnNote) {
        this.user1PkhdnNote = user1PkhdnNote;
    }

    @Column(name = "USER2_PKHDN", length = 10)
    public String getUser2Pkhdn() {
        return this.user2Pkhdn;
    }

    public void setUser2Pkhdn(String user2Pkhdn) {
        this.user2Pkhdn = user2Pkhdn;
    }

    @Column(name = "USER2_PKHDN_DATE", precision = 17, scale = 0)
    public Long getUser2PkhdnDate() {
        return this.user2PkhdnDate;
    }

    public void setUser2PkhdnDate(Long user2PkhdnDate) {
        this.user2PkhdnDate = user2PkhdnDate;
    }

    @Column(name = "USER2_PKHDN_NOTE", length = 250)
    public String getUser2PkhdnNote() {
        return this.user2PkhdnNote;
    }

    public void setUser2PkhdnNote(String user2PkhdnNote) {
        this.user2PkhdnNote = user2PkhdnNote;
    }

    @Column(name = "USER1_PTNT", length = 10)
    public String getUser1Ptnt() {
        return this.user1Ptnt;
    }

    public void setUser1Ptnt(String user1Ptnt) {
        this.user1Ptnt = user1Ptnt;
    }

    @Column(name = "USER1_PTNT_DATE", precision = 17, scale = 0)
    public Long getUser1PtntDate() {
        return this.user1PtntDate;
    }

    public void setUser1PtntDate(Long user1PtntDate) {
        this.user1PtntDate = user1PtntDate;
    }

    @Column(name = "USER1_PTNT_NOTE", length = 250)
    public String getUser1PtntNote() {
        return this.user1PtntNote;
    }

    public void setUser1PtntNote(String user1PtntNote) {
        this.user1PtntNote = user1PtntNote;
    }

    @Column(name = "USER2_PTNT", length = 10)
    public String getUser2Ptnt() {
        return this.user2Ptnt;
    }

    public void setUser2Ptnt(String user2Ptnt) {
        this.user2Ptnt = user2Ptnt;
    }

    @Column(name = "USER2_PTNT_DATE", precision = 17, scale = 0)
    public Long getUser2PtntDate() {
        return this.user2PtntDate;
    }

    public void setUser2PtntDate(Long user2PtntDate) {
        this.user2PtntDate = user2PtntDate;
    }

    @Column(name = "USER2_PTNT_NOTE", length = 250)
    public String getUser2PtntNote() {
        return this.user2PtntNote;
    }

    public void setUser2PtntNote(String user2PtntNote) {
        this.user2PtntNote = user2PtntNote;
    }

    @Column(name = "CN_QUANLY", length = 50)
    public String getCnQuanly() {
        return this.cnQuanly;
    }

    public void setCnQuanly(String cnQuanly) {
        this.cnQuanly = cnQuanly;
    }

    @Column(name = "STATUS_DUYET", precision = 2, scale = 0)
    public Byte getStatusDuyet() {
        return this.statusDuyet;
    }

    public void setStatusDuyet(Byte statusDuyet) {
        this.statusDuyet = statusDuyet;
    }

    @Column(name = "STATUS_DVCNT", precision = 2, scale = 0)
    public Byte getStatusDvcnt() {
        return this.statusDvcnt;
    }

    public void setStatusDvcnt(Byte statusDvcnt) {
        this.statusDvcnt = statusDvcnt;
    }

    @Column(name = "HANMUC_VND", precision = 10, scale = 0)
    public Long getHanmucVnd() {
        return this.hanmucVnd;
    }

    public void setHanmucVnd(Long hanmucVnd) {
        this.hanmucVnd = hanmucVnd;
    }

    @Column(name = "HANMUC_USD", precision = 10, scale = 0)
    public Long getHanmucUsd() {
        return this.hanmucUsd;
    }

    public void setHanmucUsd(Long hanmucUsd) {
        this.hanmucUsd = hanmucUsd;
    }

    @Column(name = "SL_LAPTHEM", precision = 2, scale = 0)
    public Byte getSllapthem() {
        return this.soluonglapthem;
    }

    public void setSllapthem(Byte Sllapthem) {
        this.soluonglapthem = Sllapthem;
    }

    @Column(name = "FILE_UPLOAD", length = 200)
    public String getFileUpload() {
        return this.fileUpload;
    }

    public void setFileUpload(String fileUpload) {
        this.fileUpload = fileUpload;
    }

    @Column(name = "FILE_UPLOAD2", length = 200)
    public String getFileUpload2() {
        return this.fileUpload2;
    }

    public void setFileUpload2(String fileUpload) {
        this.fileUpload2 = fileUpload;
    }

    @Column(name = "EDIT1", length = 200)
    public String getedit1() {
        return this.edit1;
    }

    public void setedit1(String edit1) {
        this.edit1 = edit1;
    }

    @Column(name = "EDIT2", length = 200)
    public String getedit2() {
        return this.edit2;
    }

    public void setedit2(String edit2) {
        this.edit2 = edit2;
    }

    @Column(name = "EDIT3", length = 200)
    public String getedit3() {
        return this.edit3;
    }

    public void setedit3(String edit3) {
        this.edit3 = edit3;
    }

    @Column(name = "EDIT4", length = 200)
    public String getedit4() {
        return this.edit4;
    }

    public void setedit4(String edit4) {
        this.edit4 = edit4;
    }

    @Column(name = "FILE_UPLOAD3", length = 200)
    public String getFileUpload3() {
        return this.fileUpload3;
    }

    public void setFileUpload3(String fileUpload3) {
        this.fileUpload3 = fileUpload3;
    }

    @Column(name = "FILEUPLOAD_TAMKHOA", length = 200)
    public String getFileuploadTamKhoa() {
        return this.fileUploadTamkhoa;
    }

    public void setFileuploadTamKhoa(String fileUploadTamkhoa) {
        this.fileUploadTamkhoa = fileUploadTamkhoa;
    }

    @Column(name = "FILEUPLOAD_KHOA", length = 200)
    public String getFileuploadKhoa() {
        return this.fileUploadkhoa;
    }

    public void setFileuploadKhoa(String fileUploadkhoa) {
        this.fileUploadkhoa = fileUploadkhoa;
    }

    @Column(name = "LOG_USER", length = 2000)
    public String getLogUser() {
        return this.logUser;
    }

    public void setLogUser(String loguser) {
        this.logUser = loguser;
    }

    @Column(name = "BBBG_THEMMOI", precision = 1, scale = 0)
    public Byte getBbbgThemmoi() {
        return this.bbbgthemmoi;
    }

    public void setBbbgThemmoi(Byte bbbgthemmoi) {
        this.bbbgthemmoi = bbbgthemmoi;
    }

    @Column(name = "BBBG_LAPTHEM", precision = 1, scale = 0)
    public Byte getBbbgLapthem() {
        return this.bbbglapthem;
    }

    public void setBbbgLapthem(Byte bbbglapthem) {
        this.bbbglapthem = bbbglapthem;
    }

    @Column(name = "BBBG_KHOA", precision = 1, scale = 0)
    public Byte getBbbgKhoa() {
        return this.bbbgkhoa;
    }

    public void setBbbgKhoa(Byte bbbgkhoa) {
        this.bbbgkhoa = bbbgkhoa;
    }

    @Column(name = "BBBG_TAMKHOA", precision = 1, scale = 0)
    public Byte getBbbgTamKhoa() {
        return this.bbbgtamkhoa;
    }

    public void setBbbgTamKhoa(Byte bbbgtamkhoa) {
        this.bbbgtamkhoa = bbbgtamkhoa;
    }

    @Column(name = "TEN_FILE_BBBG", length = 200)
    public String getTenFileBbbg() {
        return this.tenFileBbbg;
    }

    public void setTenFileBbbg(String tenFileBbbg) {
        this.tenFileBbbg = tenFileBbbg;
    }

    @Column(name = "DIRECT_NAME", length = 150)
    public String getDirectName() {
        return directName;
    }

    public void setDirectName(String directName) {
        this.directName = directName;
    }

    @Column(name = "INDIRECT_NAME", length = 150)
    public String getIndirectName() {
        return indirectName;
    }

    public void setIndirectName(String indirectName) {
        this.indirectName = indirectName;
    }

    @Column(name = "DIRECT_CODE", length = 5)
    public String getDirectCode() {
        return directCode;
    }

    public void setDirectCode(String directCode) {
        this.directCode = directCode;
    }

    @Column(name = "INDIRECT_CODE", length = 5)
    public String getIndirectCode() {
        return indirectCode;
    }

    public void setIndirectCode(String indirectCode) {
        this.indirectCode = indirectCode;
    }

    @Column(name = "DIRECT_JOBTILE_CODE", length = 10)
    public String getDirectJobtitleCode() {
        return directJobtitleCode;
    }

    public void setDirectJobtitleCode(String directJobtitleCode) {
        this.directJobtitleCode = directJobtitleCode;
    }

    @Column(name = "INDIRECT_JOBTILE_CODE", length = 10)
    public String getIndirectJobtitleCode() {
        return indirectJobtitleCode;
    }

    public void setIndirectJobtitleCode(String indirectJobtitleCode) {
        this.indirectJobtitleCode = indirectJobtitleCode;
    }

    @Column(name = "DIRECT_JOBTILE_NAME", length = 150)
    public String getDirectJobtitleName() {
        return directJobtitleName;
    }

    public void setDirectJobtitleName(String directJobtitleName) {
        this.directJobtitleName = directJobtitleName;
    }

    @Column(name = "INDIRECT_JOBTILE_NAME", length = 150)
    public String getIndirectJobtitleName() {
        return indirectJobtitleName;
    }

    public void setIndirectJobtitleName(String indirectJobtitleName) {
        this.indirectJobtitleName = indirectJobtitleName;
    }

    @Column(name = "DIRECT_BRANCH_NAME", length = 50)
    public String getDirectBranchName() {
        return directBranchName;
    }

    public void setDirectBranchName(String directBranchName) {
        this.directBranchName = directBranchName;
    }

    @Column(name = "INDIRECT_BRANCH_NAME", length = 50)
    public String getIndirectBranchName() {
        return indirectBranchName;
    }

    public void setIndirectBranchName(String indirectBranchName) {
        this.indirectBranchName = indirectBranchName;
    }

    @Column(name = "THOI_GIAN_LAP_DAT", precision = 8, scale = 0)
    public Integer getThoiGianLapDat() {
        return this.thoiGianLapDat;
    }

    public void setThoiGianLapDat(Integer thoiGianLapDat) {
        this.thoiGianLapDat = thoiGianLapDat;
    }

    @Column(name = "LOAI_KHACH_HANG", length = 50)
    public String getLoaiKhachHang() {
        return this.loaiKhachHang;
    }

    public void setLoaiKhachHang(String loaiKhachHang) {
        this.loaiKhachHang = loaiKhachHang;
    }

    @Column(name = "LOAI_DOANH_NGHIEP", length = 10)
    public String getLoaiDoanhNghiep() {
        return this.loaiDoanhNghiep;
    }

    public void setLoaiDoanhNghiep(String loaiDoanhNghiep) {
        this.loaiDoanhNghiep = loaiDoanhNghiep;
    }

    @Column(name = "FILE_MAPPING", length = 200)
    public String getFileMapping() {
        return this.fileMapping;
    }

    public void setFileMapping(String fileMapping) {
        this.fileMapping = fileMapping;
    }
}
