package entity;
// Generated Nov 7, 2017 10:06:23 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserAcc generated by hbm2java
 */
@Entity
@Table(name = "TT_HISTAFF", schema = "CCPS"
)
public class TtHistaff implements java.io.Serializable {

    private String empCode;
    private String empName;
    private String branchCode;
    private String branchName;
    private String jobtitleCode;
    private String jobtitleName;
    private String branchCodeGoc;
    private String branchNameGoc;
    private String jobtitleCodeGoc;
    private String jobtitleNameGoc;
    private String emailScb;
    private String cardNo;
    private String ngayvao;
    private String thuviec;
    private String chinhthuc;
    private String nhomnv;

    public TtHistaff() {
    }

    public TtHistaff(String empCode) {
        this.empCode = empCode;
    }

    public TtHistaff(String empCode, String empName, String branchCode, String branchName,
            String jobtitleCode, String jobtitleName, String branchCodeGoc, String branchNameGoc,
            String jobtitleCodeGoc, String jobtitleNameGoc, String emailScb, String cardNo,
            String ngayvao, String thuviec, String chinhthuc, String nhomnv) {
        this.empCode = empCode;
        this.empName = empName;
        this.branchCode = branchCode;
        this.branchName = branchName;

    }

    @Id
    @Column(name = "EMP_CODE", unique = true, nullable = false, length = 20)
    public String getEmpCode() {
        return empCode;
    }

    public void setEmpCode(String empCode) {
        this.empCode = empCode;
    }

    @Column(name = "EMP_NAME", length = 100)
    public String getEmpName() {
        return empName;
    }

    public void setEmpName(String empName) {
        this.empName = empName;
    }

    @Column(name = "BRANCH_CODE", length = 4)
    public String getBranchCode() {
        return branchCode;
    }

    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    @Column(name = "BRANCH_NAME", length = 400)
    public String getBranchName() {
        return branchName;
    }

    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    @Column(name = "JOBTILE_CODE", length = 10)
    public String getJobtitleCode() {
        return jobtitleCode;
    }

    public void setJobtitleCode(String jobtitleCode) {
        this.jobtitleCode = jobtitleCode;
    }

    @Column(name = "JOBTITLE_NAME", length = 200)
    public String getJobtitleName() {
        return jobtitleName;
    }

    public void setJobtitleName(String jobtitleName) {
        this.jobtitleName = jobtitleName;
    }

    @Column(name = "BRANCH_CODE_GOC", length = 4)
    public String getBranchCodeGoc() {
        return branchCodeGoc;
    }

    public void setBranchCodeGoc(String branchCodeGoc) {
        this.branchCodeGoc = branchCodeGoc;
    }

    @Column(name = "BRANCH_NAME_GOC", length = 400)
    public String getBranchNameGoc() {
        return branchNameGoc;
    }

    public void setBranchNameGoc(String branchNameGoc) {
        this.branchNameGoc = branchNameGoc;
    }

    @Column(name = "JOBTILE_CODE_GOC", length = 10)
    public String getJobtitleCodeGoc() {
        return jobtitleCodeGoc;
    }

    public void setJobtitleCodeGoc(String jobtitleCodeGoc) {
        this.jobtitleCodeGoc = jobtitleCodeGoc;
    }

    @Column(name = "JOBTITLE_NAME_GOC", length = 200)
    public String getJobtitleNameGoc() {
        return jobtitleNameGoc;
    }

    public void setJobtitleNameGoc(String jobtitleNameGoc) {
        this.jobtitleNameGoc = jobtitleNameGoc;
    }

    @Column(name = "EMAIL_SCB", length = 100)
    public String getEmailScb() {
        return emailScb;
    }

    public void setEmailScb(String emailScb) {
        this.emailScb = emailScb;
    }

    @Column(name = "CARD_NO", length = 20)
    public String getCardNo() {
        return cardNo;
    }

    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    @Column(name = "NGAYVAO", length = 50)
    public String getNgayvao() {
        return ngayvao;
    }

    public void setNgayvao(String ngayvao) {
        this.ngayvao = ngayvao;
    }

    @Column(name = "THUVIEC", length = 50)
    public String getThuviec() {
        return thuviec;
    }

    public void setThuviec(String thuviec) {
        this.thuviec = thuviec;
    }

    @Column(name = "CHINHTHUC", length = 50)
    public String getChinhthuc() {
        return chinhthuc;
    }

    public void setChinhthuc(String chinhthuc) {
        this.chinhthuc = chinhthuc;
    }

    @Column(name = "NHOMNV", length = 3)
    public String getNhomnv() {
        return nhomnv;
    }

    public void setNhomnv(String nhomnv) {
        this.nhomnv = nhomnv;
    }
}
