package entity;
// Generated Nov 1, 2017 2:47:34 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TtPosTemp generated by hbm2java
 */
@Entity
@Table(name = "TT_LOG_DVCNT", schema = "CCPS")
public class TtLogDvcnt implements java.io.Serializable {

    private long logId;
    private String logMid;
    private long logTime;
    private String logUser;
    private Byte logLevel;
    private String logContent;

    public TtLogDvcnt() {
    }

    public TtLogDvcnt(long logId) {
        this.logId = logId;
    }

    @Id
    @GeneratedValue(generator = "my_seq")
    @SequenceGenerator(name = "my_seq", sequenceName = "INCREMENT_LOGID")
    @Column(name = "LOG_ID", unique = true, nullable = false, precision = 10, scale = 0)
    public long getLogId() {
        return logId;
    }

    public void setLogId(long logId) {
        this.logId = logId;
    }

    @Column(name = "LOG_MID", length = 10)
    public String getLogMid() {
        return logMid;
    }

    public void setLogMid(String logMid) {
        this.logMid = logMid;
    }

    @Column(name = "LOG_TIME", precision = 17, scale = 0)
    public long getLogTime() {
        return logTime;
    }

    public void setLogTime(long logTime) {
        this.logTime = logTime;
    }

    @Column(name = "LOG_USER", length = 10)
    public String getLogUser() {
        return logUser;
    }

    public void setLogUser(String logUser) {
        this.logUser = logUser;
    }

    @Column(name = "LOG_LEVEL", precision = 1, scale = 0)
    public Byte getLogLevel() {
        return logLevel;
    }

    public void setLogLevel(Byte logLevel) {
        this.logLevel = logLevel;
    }

    @Column(name = "LOG_CONTENT", length = 2000)
    public String getLogContent() {
        return logContent;
    }

    public void setLogContent(String logContent) {
        this.logContent = logContent;
    }    
}
