package entity;
// Generated Oct 30, 2017 8:31:15 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TtPos generated by hbm2java
 */
@Entity
@Table(name = "TT_POS_LIVE", schema = "CCPS"
)
public class TtPosLive implements java.io.Serializable {

    private String maPos;
    private String dongmay;
    private String soseri;
    private String mid;
    private String mataisan;
    private String sototrinh;
    private Integer ngaynhapkho;
    private String usernhap;
    private String ghichu;
    private String tinhtrangPos;
    private String donviQuanly;
    private String chinhanhQuanly;
    private String tinhtrangDuyet;
    private String teninhoadon;
    private String diachiLapdat;
    private String soTktgtt;
    private String tenchutk;
    private String nganhang;
    private String tid1;
    private String mid1;
    private String tid2;
    private String mid2;
    private String tid3;
    private String mid3;
    private String tenDvcnt;
    private String mcc;
    private Long hanmucVnd;
    private Long hanmucUsd;
    private Byte soluonglapthem;
    private String loaitien;
    private Long phimo;
    private Byte gddb1;
    private Byte gddb2;
    private Byte gddb3;
    private Byte gddb4;
    private Byte gddb5;
    private Byte gddb6;
    private Byte gddb7;
    private Byte gddb8;
    private Byte gddb9;
    private Byte tinhtrang;
    private String tenNganhNghe;
    private String mccCode;
    private String merchantType;
    private String vungLapdat;
    private String userLapdat;
    private String noiLuuPos;
    private String userThuHoi;
    private Integer ngayXacnhanThuhoi;

    public TtPosLive() {
    }

    public TtPosLive(String maPos) {
        this.maPos = maPos;
    }

    public TtPosLive(String maPos, String dongmay, String soseri, String mid, String mataisan,
            String sototrinh, Integer ngaynhapkho, String usernhap, String ghichu,
            String tinhtrangPos, String donviQuanly, String chinhanhQuanly,
            String tinhtrangDuyet, String teninhoadon, String diachiLapdat,
            String soTktgtt, String tenchutk, String nganhang, String tid1, String mid1,
            String tid2, String mid2, String tid3, String mid3, String tenDvcnt,
            String mcc, Long hanmucVnd, Long hanmucUsd, Byte soluonglapthem,
            String loaitien, Long phimo, Byte gddb1, Byte gddb2, Byte gddb3,
            Byte gddb4, Byte gddb5, Byte gddb6, Byte gddb7, Byte gddb8,
            Byte gddb9, Byte tinhtrang, String tenNganhNghe) {
        this.maPos = maPos;
        this.dongmay = dongmay;
        this.soseri = soseri;
        this.mid = mid;
        this.mataisan = mataisan;
        this.sototrinh = sototrinh;
        this.ngaynhapkho = ngaynhapkho;
        this.usernhap = usernhap;
        this.ghichu = ghichu;
        this.tinhtrangPos = tinhtrangPos;
        this.donviQuanly = donviQuanly;
        this.chinhanhQuanly = chinhanhQuanly;
        this.tinhtrangDuyet = tinhtrangDuyet;
        this.teninhoadon = teninhoadon;
        this.diachiLapdat = diachiLapdat;
        this.soTktgtt = soTktgtt;
        this.tenchutk = tenchutk;
        this.nganhang = nganhang;
        this.tid1 = tid1;
        this.mid1 = mid1;
        this.tid2 = tid2;
        this.mid2 = mid2;
        this.tid3 = tid3;
        this.mid3 = mid3;
        this.tenDvcnt = tenDvcnt;
        this.mcc = mcc;
        this.hanmucUsd = hanmucUsd;
        this.hanmucVnd = hanmucVnd;
        this.soluonglapthem = soluonglapthem;
        this.loaitien = loaitien;
        this.phimo = phimo;
        this.gddb1 = gddb1;
        this.gddb2 = gddb2;
        this.gddb3 = gddb3;
        this.gddb4 = gddb4;
        this.gddb5 = gddb5;
        this.gddb6 = gddb6;
        this.gddb7 = gddb7;
        this.gddb8 = gddb8;
        this.tinhtrang = tinhtrang;
        this.tenNganhNghe = tenNganhNghe;
    }

    @Id

    @Column(name = "MA_POS", unique = true, nullable = false, length = 10)
    public String getMaPos() {
        return this.maPos;
    }

    public void setMaPos(String maPos) {
        this.maPos = maPos;
    }

    @Column(name = "DONGMAY", length = 8)
    public String getDongmay() {
        return this.dongmay;
    }

    public void setDongmay(String dongmay) {
        this.dongmay = dongmay;
    }

    @Column(name = "SOSERI", length = 20)
    public String getSoseri() {
        return this.soseri;
    }

    public void setSoseri(String soseri) {
        this.soseri = soseri;
    }

    @Column(name = "MID", length = 10)
    public String getMid() {
        return this.mid;
    }

    public void setMid(String mid) {
        this.mid = mid;
    }

    @Column(name = "MATAISAN", length = 20)
    public String getMataisan() {
        return this.mataisan;
    }

    public void setMataisan(String mataisan) {
        this.mataisan = mataisan;
    }

    @Column(name = "SOTOTRINH", length = 20)
    public String getSototrinh() {
        return this.sototrinh;
    }

    public void setSototrinh(String sototrinh) {
        this.sototrinh = sototrinh;
    }

    @Column(name = "NGAYNHAPKHO", precision = 8, scale = 0)
    public Integer getNgaynhapkho() {
        return this.ngaynhapkho;
    }

    public void setNgaynhapkho(Integer ngaynhapkho) {
        this.ngaynhapkho = ngaynhapkho;
    }

    @Column(name = "USERNHAP", length = 10)
    public String getUsernhap() {
        return this.usernhap;
    }

    public void setUsernhap(String usernhap) {
        this.usernhap = usernhap;
    }

    @Column(name = "GHICHU", length = 200)
    public String getGhichu() {
        return this.ghichu;
    }

    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }

    @Column(name = "TINHTRANG_POS", length = 20)
    public String getTinhtrangPos() {
        return this.tinhtrangPos;
    }

    public void setTinhtrangPos(String tinhtrangPos) {
        this.tinhtrangPos = tinhtrangPos;
    }

    @Column(name = "DONVI_QUANLY", length = 10)
    public String getDonviQuanly() {
        return this.donviQuanly;
    }

    public void setDonviQuanly(String donviQuanly) {
        this.donviQuanly = donviQuanly;
    }

    @Column(name = "CHINHANH_QUANLY", length = 10)
    public String getChinhanhQuanly() {
        return this.chinhanhQuanly;
    }

    public void setChinhanhQuanly(String chinhanhQuanly) {
        this.chinhanhQuanly = chinhanhQuanly;
    }

    @Column(name = "TINHTRANG_DUYET", length = 20)
    public String getTinhtrangDuyet() {
        return this.tinhtrangDuyet;
    }

    public void setTinhtrangDuyet(String tinhtrangDuyet) {
        this.tinhtrangDuyet = tinhtrangDuyet;
    }

    @Column(name = "TENINHOADON", length = 22)
    public String getTeninhoadon() {
        return this.teninhoadon;
    }

    public void setTeninhoadon(String teninhoadon) {
        this.teninhoadon = teninhoadon;
    }

    @Column(name = "DIACHI_LAPDAT", length = 50)
    public String getDiachiLapdat() {
        return this.diachiLapdat;
    }

    public void setDiachiLapdat(String diachiLapdat) {
        this.diachiLapdat = diachiLapdat;
    }

    @Column(name = "SO_TKTGTT", length = 20)
    public String getSoTktgtt() {
        return this.soTktgtt;
    }

    public void setSoTktgtt(String soTktgtt) {
        this.soTktgtt = soTktgtt;
    }

    @Column(name = "TENCHUTK", length = 50)
    public String getTenchutk() {
        return this.tenchutk;
    }

    public void setTenchutk(String tenchutk) {
        this.tenchutk = tenchutk;
    }

    @Column(name = "NGANHANG", length = 20)
    public String getNganhang() {
        return this.nganhang;
    }

    public void setNganhang(String nganhang) {
        this.nganhang = nganhang;
    }

    @Column(name = "TID1", length = 20)
    public String getTid1() {
        return this.tid1;
    }

    public void setTid1(String tid1) {
        this.tid1 = tid1;
    }

    @Column(name = "MID1", length = 20)
    public String getMid1() {
        return this.mid1;
    }

    public void setMid1(String mid1) {
        this.mid1 = mid1;
    }

    @Column(name = "TID2", length = 20)
    public String getTid2() {
        return this.tid2;
    }

    public void setTid2(String tid2) {
        this.tid2 = tid2;
    }

    @Column(name = "MID2", length = 20)
    public String getMid2() {
        return this.mid2;
    }

    public void setMid2(String mid2) {
        this.mid2 = mid2;
    }

    @Column(name = "TID3", length = 20)
    public String getTid3() {
        return this.tid3;
    }

    public void setTid3(String tid3) {
        this.tid3 = tid3;
    }

    @Column(name = "MID3", length = 20)
    public String getMid3() {
        return this.mid3;
    }

    public void setMid3(String mid3) {
        this.mid3 = mid3;
    }

    @Column(name = "TEN_DVCNT", length = 50)
    public String getTenDvcnt() {
        return this.tenDvcnt;
    }

    public void setTenDvcnt(String tenDvcnt) {
        this.tenDvcnt = tenDvcnt;
    }

    @Column(name = "MCC", length = 4)
    public String getMcc() {
        return this.mcc;
    }

    public void setMcc(String mcc) {
        this.mcc = mcc;
    }

    @Column(name = "HANMUC_VND", precision = 10, scale = 0)
    public Long getHanmucVnd() {
        return this.hanmucVnd;
    }

    public void setHanmucVnd(Long hanmucVnd) {
        this.hanmucVnd = hanmucVnd;
    }

    @Column(name = "HANMUC_USD", precision = 10, scale = 0)
    public Long getHanmucUsd() {
        return this.hanmucUsd;
    }

    public void setHanmucUsd(Long hanmucUsd) {
        this.hanmucUsd = hanmucUsd;
    }

    @Column(name = "SL_LAPTHEM", precision = 2, scale = 0)
    public Byte getSllapthem() {
        return this.soluonglapthem;
    }

    public void setSllapthem(Byte Sllapthem) {
        this.soluonglapthem = Sllapthem;
    }

    @Column(name = "LOAITIEN", length = 21)
    public String getLoaitien() {
        return this.loaitien;
    }

    public void setLoaitien(String Loaitien) {
        this.loaitien = Loaitien;
    }

    @Column(name = "PHI_MO", precision = 10, scale = 0)
    public Long getPhimo() {
        return this.phimo;
    }

    public void setPhimo(Long phimo) {
        this.phimo = phimo;
    }

    @Column(name = "GDDB1", precision = 1, scale = 0)
    public Byte getGddb1() {
        return this.gddb1;
    }

    public void setGddb1(Byte gddb1) {
        this.gddb1 = gddb1;
    }

    @Column(name = "GDDB2", precision = 1, scale = 0)
    public Byte getGddb2() {
        return this.gddb2;
    }

    public void setGddb2(Byte gddb2) {
        this.gddb2 = gddb2;
    }

    @Column(name = "GDDB3", precision = 1, scale = 0)
    public Byte getGddb3() {
        return this.gddb3;
    }

    public void setGddb3(Byte gddb3) {
        this.gddb3 = gddb3;
    }

    @Column(name = "GDDB4", precision = 1, scale = 0)
    public Byte getGddb4() {
        return this.gddb4;
    }

    public void setGddb4(Byte gddb4) {
        this.gddb4 = gddb4;
    }

    @Column(name = "GDDB5", precision = 1, scale = 0)
    public Byte getGddb5() {
        return this.gddb5;
    }

    public void setGddb5(Byte gddb5) {
        this.gddb5 = gddb5;
    }

    @Column(name = "GDDB6", precision = 1, scale = 0)
    public Byte getGddb6() {
        return this.gddb6;
    }

    public void setGddb6(Byte gddb6) {
        this.gddb6 = gddb6;
    }

    @Column(name = "GDDB7", precision = 1, scale = 0)
    public Byte getGddb7() {
        return this.gddb7;
    }

    public void setGddb7(Byte gddb7) {
        this.gddb7 = gddb7;
    }

    @Column(name = "GDDB8", precision = 1, scale = 0)
    public Byte getGddb8() {
        return this.gddb8;
    }

    public void setGddb8(Byte gddb8) {
        this.gddb8 = gddb8;
    }

    @Column(name = "GDDB9", precision = 1, scale = 0)
    public Byte getGddb9() {
        return this.gddb9;
    }

    public void setGddb9(Byte gddb9) {
        this.gddb9 = gddb9;
    }

    @Column(name = "TINHTRANG", precision = 1, scale = 0)
    public Byte getTinhtrang() {
        return this.tinhtrang;
    }

    public void setTinhtrang(Byte tinhtrang) {
        this.tinhtrang = tinhtrang;
    }

    @Column(name = "TEN_NGANH_NGHE", length = 1)
    public String getTenNganhNghe() {
        return this.tenNganhNghe;
    }

    public void setTenNganhNghe(String tenNganhNghe) {
        this.tenNganhNghe = tenNganhNghe;
    }

    @Column(name = "MCC_CODE", precision = 8, scale = 0)
    public String getMccCode() {
        return mccCode;
    }

    public void setMccCode(String mccCode) {
        this.mccCode = mccCode;
    }

    @Column(name = "MERCHANT_TYPE", length = 500)
    public String getMerchantType() {
        return merchantType;
    }

    public void setMerchantType(String merchantType) {
        this.merchantType = merchantType;
    }

    @Column(name = "VUNG_LAPDAT", length = 30)
    public String getVungLapdat() {
        return vungLapdat;
    }

    public void setVungLapdat(String vungLapdat) {
        this.vungLapdat = vungLapdat;
    }

    @Column(name = "USER_LAPDAT", length = 50)
    public String getUserLapdat() {
        return userLapdat;
    }

    public void setUserLapdat(String userLapdat) {
        this.userLapdat = userLapdat;
    }

    @Column(name = "NOI_LUU_POS", length = 50)
    public String getNoiLuuPos() {
        return noiLuuPos;
    }

    public void setNoiLuuPos(String noiLuuPos) {
        this.noiLuuPos = noiLuuPos;
    }

    @Column(name = "USER_THUHOI_POS", length = 50)
    public String getUserThuHoi() {
        return userThuHoi;
    }

    public void setUserThuHoi(String userThuHoi) {
        this.userThuHoi = userThuHoi;
    }

    @Column(name = "NGAY_XACNHAN_THUHOI", precision = 8, scale = 0)
    public Integer getngayXacnhanThuhoi() {
        return this.ngayXacnhanThuhoi;
    }

    public void setngayXacnhanThuhoi(Integer ngayXacnhanThuhoi) {
        this.ngayXacnhanThuhoi = ngayXacnhanThuhoi;
    }
}
