package entity;
// Generated Nov 1, 2017 2:47:34 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TtPosTemp generated by hbm2java
 */
@Entity
@Table(name = "TT_POS_TEMP_LIVE", schema = "CCPS")
public class TtPosTempLive implements java.io.Serializable {

    private long stt;
    private String mid;
    private String dongmay;
    private String ghichu;
    private String teninhoadon;
    private String diachiLapdat;
    private String soTktgtt;
    private String tenchutk;
    private String tenDvcnt;
    private Byte ismapping;
    private String tid1;
    private String mid1;
    private String tid2;
    private String mid2;
    private String tid3;
    private String mid3;
    private String soseri;
    private Long hanmucVnd;
    private Long hanmucUsd;
    private Byte soluonglapthem;
    private String loaitien;
    private Long phimo;
    private Byte gddb1;
    private Byte gddb2;
    private Byte gddb3;
    private Byte gddb4;
    private Byte gddb5;
    private Byte gddb6;
    private Byte gddb7;
    private Byte gddb8;
    private Byte gddb9;
    private String mcc;
    private String gpdkkdso;
    private String gpdkkdTennguoidaidien;
    private String gpdkkdCmnd;
    private String diachiDvcnt;
    private Long user1PtntDate;
    private String nganhnghekd;
    private String edit1;
    private String edit2;
    private String edit3;
    private String edit4;
    private Byte editgddb1;
    private Byte editgddb2;
    private Byte editgddb3;
    private Byte editgddb4;
    private Byte editgddb5;
    private Byte editgddb6;
    private Byte editgddb7;
    private Byte editgddb8;
    private Byte editgddb9;
    private Byte tinhtrang;
    private String soseriDukien;
    private String tenNganhNghe;
    private String mccCode;
    private String merchantType;
    private String vungLapdat;

    public TtPosTempLive() {
    }

    public TtPosTempLive(long stt) {
        this.stt = stt;
    }

    public TtPosTempLive(long stt, String mid, String dongmay, String ghichu,
            String teninhoadon, String diachiLapdat, String soTktgtt,
            String tenchutk, String tenDvcnt, Byte ismapping, String tid1,
            String mid1, String tid2, String mid2, String tid3, String mid3,
            String soseri, Long hanmucVnd, Long hanmucUsd, Byte soluonglapthem,
            String loaitien, Long phimo, Byte gddb1, Byte gddb2, Byte gddb3,
            Byte gddb4, Byte gddb5, Byte gddb6, Byte gddb7, Byte gddb8,
            Byte gddb9, String mcc, String gpdkkdso, String gpdkkdTennguoidaidien,
            String gpdkkdCmnd, String diachiDvcnt, Long user1PtntDate, String nganhnghekd,
            String edit1, String edit2, String edit3, String edit4, Byte editgddb1,
            Byte editgddb2, Byte editgddb3, Byte editgddb4, Byte editgddb5,
            Byte editgddb6, Byte editgddb7, Byte editgddb8, Byte editgddb9,
            Byte tinhtrang, String soseriDukien, String tenNganhNghe) {
        this.stt = stt;
        this.mid = mid;
        this.dongmay = dongmay;
        this.ghichu = ghichu;
        this.teninhoadon = teninhoadon;
        this.diachiLapdat = diachiLapdat;
        this.soTktgtt = soTktgtt;
        this.tenchutk = tenchutk;
        this.tenDvcnt = tenDvcnt;
        this.ismapping = this.ismapping;
        this.tid1 = tid1;
        this.mid1 = mid1;
        this.tid2 = tid2;
        this.mid2 = mid2;
        this.tid3 = tid3;
        this.mid3 = mid3;
        this.soseri = soseri;
        this.hanmucUsd = hanmucUsd;
        this.hanmucVnd = hanmucVnd;
        this.soluonglapthem = soluonglapthem;
        this.loaitien = loaitien;
        this.phimo = phimo;
        this.gddb1 = gddb1;
        this.gddb2 = gddb2;
        this.gddb3 = gddb3;
        this.gddb4 = gddb4;
        this.gddb5 = gddb5;
        this.gddb6 = gddb6;
        this.gddb7 = gddb7;
        this.gddb8 = gddb8;
        this.mcc = mcc;
        this.gpdkkdso = gpdkkdso;
        this.gpdkkdTennguoidaidien = gpdkkdTennguoidaidien;
        this.gpdkkdCmnd = gpdkkdCmnd;
        this.diachiDvcnt = diachiDvcnt;
        this.user1PtntDate = user1PtntDate;
        this.nganhnghekd = nganhnghekd;
        this.edit1 = edit1;
        this.edit2 = edit2;
        this.edit3 = edit3;
        this.edit4 = edit4;
        this.editgddb1 = editgddb1;
        this.editgddb2 = editgddb2;
        this.editgddb3 = editgddb3;
        this.editgddb4 = editgddb4;
        this.editgddb5 = editgddb5;
        this.editgddb6 = editgddb6;
        this.editgddb7 = editgddb7;
        this.editgddb8 = editgddb8;
        this.editgddb9 = editgddb9;
        this.tinhtrang = tinhtrang;
        this.soseriDukien = soseriDukien;
        this.tenNganhNghe = tenNganhNghe;
    }

    @Id
    @GeneratedValue(generator = "my_seq")
    @SequenceGenerator(name = "my_seq", sequenceName = "SEQ_TTPOSTEMP")
    @Column(name = "STT", unique = true, nullable = false, precision = 10, scale = 0)
    public long getStt() {
        return this.stt;
    }

    public void setStt(long stt) {
        this.stt = stt;
    }

    @Column(name = "MID", length = 50)
    public String getMid() {
        return this.mid;
    }

    public void setMid(String mid) {
        this.mid = mid;
    }

    @Column(name = "DONGMAY", length = 8)
    public String getDongmay() {
        return this.dongmay;
    }

    public void setDongmay(String dongmay) {
        this.dongmay = dongmay;
    }

    @Column(name = "GHICHU", length = 200)
    public String getGhichu() {
        return this.ghichu;
    }

    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }

    @Column(name = "TENINHOADON", length = 50)
    public String getTeninhoadon() {
        return this.teninhoadon;
    }

    public void setTeninhoadon(String teninhoadon) {
        this.teninhoadon = teninhoadon;
    }

    @Column(name = "DIACHI_LAPDAT", length = 50)
    public String getDiachiLapdat() {
        return this.diachiLapdat;
    }

    public void setDiachiLapdat(String diachiLapdat) {
        this.diachiLapdat = diachiLapdat;
    }

    @Column(name = "SO_TKTGTT", length = 20)
    public String getSoTktgtt() {
        return this.soTktgtt;
    }

    public void setSoTktgtt(String soTktgtt) {
        this.soTktgtt = soTktgtt;
    }

    @Column(name = "TENCHUTK", length = 100)
    public String getTenchutk() {
        return this.tenchutk;
    }

    public void setTenchutk(String tenchutk) {
        this.tenchutk = tenchutk;
    }

    @Column(name = "TEN_DVCNT", length = 100)
    public String getTenDvcnt() {
        return this.tenDvcnt;
    }

    public void setTenDvcnt(String tenDvcnt) {
        this.tenDvcnt = tenDvcnt;
    }

    @Column(name = "ISMAPPING", precision = 2, scale = 0)
    public Byte getIsmapping() {
        return this.ismapping;
    }

    public void setIsmapping(Byte ismapping) {
        this.ismapping = ismapping;
    }

    @Column(name = "TID1", length = 20)
    public String getTid1() {
        return this.tid1;
    }

    public void setTid1(String tid1) {
        this.tid1 = tid1;
    }

    @Column(name = "MID1", length = 20)
    public String getMid1() {
        return this.mid1;
    }

    public void setMid1(String mid1) {
        this.mid1 = mid1;
    }

    @Column(name = "TID2", length = 20)
    public String getTid2() {
        return this.tid2;
    }

    public void setTid2(String tid2) {
        this.tid2 = tid2;
    }

    @Column(name = "MID2", length = 20)
    public String getMid2() {
        return this.mid2;
    }

    public void setMid2(String mid2) {
        this.mid2 = mid2;
    }

    @Column(name = "TID3", length = 20)
    public String getTid3() {
        return this.tid3;
    }

    public void setTid3(String tid3) {
        this.tid3 = tid3;
    }

    @Column(name = "MID3", length = 20)
    public String getMid3() {
        return this.mid3;
    }

    public void setMid3(String mid3) {
        this.mid3 = mid3;
    }

    @Column(name = "SOSERI", length = 20)
    public String getSoseri() {
        return this.soseri;
    }

    public void setSoseri(String soseri) {
        this.soseri = soseri;
    }

    @Column(name = "HANMUC_VND", precision = 10, scale = 0)
    public Long getHanmucVnd() {
        return this.hanmucVnd;
    }

    public void setHanmucVnd(Long hanmucVnd) {
        this.hanmucVnd = hanmucVnd;
    }

    @Column(name = "HANMUC_USD", precision = 10, scale = 0)
    public Long getHanmucUsd() {
        return this.hanmucUsd;
    }

    public void setHanmucUsd(Long hanmucUsd) {
        this.hanmucUsd = hanmucUsd;
    }

    @Column(name = "SL_LAPTHEM", precision = 2, scale = 0)
    public Byte getSllapthem() {
        return this.soluonglapthem;
    }

    public void setSllapthem(Byte Sllapthem) {
        this.soluonglapthem = Sllapthem;
    }

    @Column(name = "LOAITIEN", length = 10)
    public String getLoaitien() {
        return this.loaitien;
    }

    public void setLoaitien(String Loaitien) {
        this.loaitien = Loaitien;
    }

    @Column(name = "PHI_MO", precision = 10, scale = 0)
    public Long getPhimo() {
        return this.phimo;
    }

    public void setPhimo(Long phimo) {
        this.phimo = phimo;
    }

    @Column(name = "GDDB1", precision = 1, scale = 0)
    public Byte getGddb1() {
        return this.gddb1;
    }

    public void setGddb1(Byte gddb1) {
        this.gddb1 = gddb1;
    }

    @Column(name = "GDDB2", precision = 1, scale = 0)
    public Byte getGddb2() {
        return this.gddb2;
    }

    public void setGddb2(Byte gddb2) {
        this.gddb2 = gddb2;
    }

    @Column(name = "GDDB3", precision = 1, scale = 0)
    public Byte getGddb3() {
        return this.gddb3;
    }

    public void setGddb3(Byte gddb3) {
        this.gddb3 = gddb3;
    }

    @Column(name = "GDDB4", precision = 1, scale = 0)
    public Byte getGddb4() {
        return this.gddb4;
    }

    public void setGddb4(Byte gddb4) {
        this.gddb4 = gddb4;
    }

    @Column(name = "GDDB5", precision = 1, scale = 0)
    public Byte getGddb5() {
        return this.gddb5;
    }

    public void setGddb5(Byte gddb5) {
        this.gddb5 = gddb5;
    }

    @Column(name = "GDDB6", precision = 1, scale = 0)
    public Byte getGddb6() {
        return this.gddb6;
    }

    public void setGddb6(Byte gddb6) {
        this.gddb6 = gddb6;
    }

    @Column(name = "GDDB7", precision = 1, scale = 0)
    public Byte getGddb7() {
        return this.gddb7;
    }

    public void setGddb7(Byte gddb7) {
        this.gddb7 = gddb7;
    }

    @Column(name = "GDDB8", precision = 1, scale = 0)
    public Byte getGddb8() {
        return this.gddb8;
    }

    public void setGddb8(Byte gddb8) {
        this.gddb8 = gddb8;
    }

    @Column(name = "GDDB9", precision = 1, scale = 0)
    public Byte getGddb9() {
        return this.gddb9;
    }

    public void setGddb9(Byte gddb9) {
        this.gddb9 = gddb9;
    }

    @Column(name = "MCC", length = 4)
    public String getMcc() {
        return this.mcc;
    }

    public void setMcc(String mcc) {
        this.mcc = mcc;
    }

    @Column(name = "GPDKKDSO", length = 50)
    public String getGpdkkdso() {
        return this.gpdkkdso;
    }

    public void setGpdkkdso(String gpdkkdso) {
        this.gpdkkdso = gpdkkdso;
    }

    @Column(name = "GPDKKD_TENNGUOIDAIDIEN", length = 50)
    public String getGpdkkdTennguoidaidien() {
        return this.gpdkkdTennguoidaidien;
    }

    public void setGpdkkdTennguoidaidien(String gpdkkdTennguoidaidien) {
        this.gpdkkdTennguoidaidien = gpdkkdTennguoidaidien;
    }

    @Column(name = "GPDKKD_CMND", length = 20)
    public String getGpdkkdCmnd() {
        return this.gpdkkdCmnd;
    }

    public void setGpdkkdCmnd(String gpdkkdCmnd) {
        this.gpdkkdCmnd = gpdkkdCmnd;
    }

    @Column(name = "DIACHI_DVCNT", length = 100)
    public String getDiachiDvcnt() {
        return this.diachiDvcnt;
    }

    public void setDiachiDvcnt(String diachiDvcnt) {
        this.diachiDvcnt = diachiDvcnt;
    }

    @Column(name = "USER1_PTNT_DATE", precision = 17, scale = 0)
    public Long getUser1PtntDate() {
        return this.user1PtntDate;
    }

    public void setUser1PtntDate(Long user1PtntDate) {
        this.user1PtntDate = user1PtntDate;
    }

    @Column(name = "NGANHNGHEKD", length = 50)
    public String getNganhnghekd() {
        return this.nganhnghekd;
    }

    public void setNganhnghekd(String nganhnghekd) {
        this.nganhnghekd = nganhnghekd;
    }

    @Column(name = "EDIT1", length = 200)
    public String getedit1() {
        return this.edit1;
    }

    public void setedit1(String edit1) {
        this.edit1 = edit1;
    }

    @Column(name = "EDIT2", length = 200)
    public String getedit2() {
        return this.edit2;
    }

    public void setedit2(String edit2) {
        this.edit2 = edit2;
    }

    @Column(name = "EDIT3", length = 200)
    public String getedit3() {
        return this.edit3;
    }

    public void setedit3(String edit3) {
        this.edit3 = edit3;
    }

    @Column(name = "EDIT4", length = 200)
    public String getedit4() {
        return this.edit4;
    }

    public void setedit4(String edit4) {
        this.edit4 = edit4;
    }

    @Column(name = "EDIT_GDDB1", precision = 1, scale = 0)
    public Byte geteditGddb1() {
        return this.editgddb1;
    }

    public void seteditGddb1(Byte editgddb1) {
        this.editgddb1 = editgddb1;
    }

    @Column(name = "EDIT_GDDB2", precision = 1, scale = 0)
    public Byte geteditGddb2() {
        return this.editgddb2;
    }

    public void seteditGddb2(Byte editgddb2) {
        this.editgddb2 = editgddb2;
    }

    @Column(name = "EDIT_GDDB3", precision = 1, scale = 0)
    public Byte geteditGddb3() {
        return this.editgddb3;
    }

    public void seteditGddb3(Byte editgddb3) {
        this.editgddb3 = editgddb3;
    }

    @Column(name = "EDIT_GDDB4", precision = 1, scale = 0)
    public Byte geteditGddb4() {
        return this.editgddb4;
    }

    public void seteditGddb4(Byte editgddb4) {
        this.editgddb4 = editgddb4;
    }

    @Column(name = "EDIT_GDDB5", precision = 1, scale = 0)
    public Byte geteditGddb5() {
        return this.editgddb5;
    }

    public void seteditGddb5(Byte editgddb5) {
        this.editgddb5 = editgddb5;
    }

    @Column(name = "EDIT_GDDB6", precision = 1, scale = 0)
    public Byte geteditGddb6() {
        return this.editgddb6;
    }

    public void seteditGddb6(Byte editgddb6) {
        this.editgddb6 = editgddb6;
    }

    @Column(name = "EDIT_GDDB7", precision = 1, scale = 0)
    public Byte geteditGddb7() {
        return this.editgddb7;
    }

    public void seteditGddb7(Byte editgddb7) {
        this.editgddb7 = editgddb7;
    }

    @Column(name = "EDIT_GDDB8", precision = 1, scale = 0)
    public Byte geteditGddb8() {
        return this.editgddb8;
    }

    public void seteditGddb8(Byte editgddb8) {
        this.editgddb8 = editgddb8;
    }

    @Column(name = "EDIT_GDDB9", precision = 1, scale = 0)
    public Byte geteditGddb9() {
        return this.editgddb9;
    }

    public void seteditGddb9(Byte editgddb9) {
        this.editgddb9 = editgddb9;
    }

    @Column(name = "TINHTRANG", precision = 1, scale = 0)
    public Byte getTinhtrang() {
        return this.tinhtrang;
    }

    public void setTinhtrang(Byte tinhtrang) {
        this.tinhtrang = tinhtrang;
    }

    @Column(name = "SOSERI_DUKIEN", length = 20)
    public String getSoseriDukien() {
        return this.soseriDukien;
    }

    public void setSoseriDukien(String soseriDukien) {
        this.soseriDukien = soseriDukien;
    }

    @Column(name = "TEN_NGANH_NGHE", length = 100)
    public String getTenNganhNghe() {
        return this.tenNganhNghe;
    }

    public void setTenNganhNghe(String tenNganhNghe) {
        this.tenNganhNghe = tenNganhNghe;
    }
    
    @Column(name = "MCC_CODE", precision = 8, scale = 0)
    public String getMccCode() {
        return mccCode;
    }

    public void setMccCode(String mccCode) {
        this.mccCode = mccCode;
    }

    @Column(name = "MERCHANT_TYPE", length = 500)
    public String getMerchantType() {
        return merchantType;
    }

    public void setMerchantType(String merchantType) {
        this.merchantType = merchantType;
    }
    
     @Column(name = "VUNG_LAPDAT", length = 30)
    public String getVungLapdat() {
        return vungLapdat;
    }

    public void setVungLapdat(String vungLapdat) {
        this.vungLapdat = vungLapdat;
    }
}
