package entity;
// Generated Nov 7, 2017 10:06:23 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserAcc generated by hbm2java
 */
@Entity
@Table(name = "USER_ACC", schema = "CCPS"
)
public class UserAcc implements java.io.Serializable {

    private String maUser;
    private String hoten;
    private String maCn;
    private String tenCn;
    private Byte groupUser;
    private Byte landangnhap;
    private String password;
    private Byte landangnhapsai;
    private Byte tinhtrang;
    private String email;

    public UserAcc() {
    }

    public UserAcc(String maUser) {
        this.maUser = maUser;
    }

    public UserAcc(String maUser, String hoten, String maCn, String tenCn, Byte groupUser,
            Byte landangnhap, String password, Byte landangnhapsai, Byte tinhtrang) {
        this.maUser = maUser;
        this.hoten = hoten;
        this.maCn = maCn;
        this.tenCn = tenCn;
        this.groupUser = groupUser;
        this.landangnhap = landangnhap;
        this.password = password;
        this.landangnhapsai = landangnhapsai;
        this.tinhtrang = tinhtrang;
    }

    @Id
    @Column(name = "MA_USER", unique = true, nullable = false, length = 10)
    public String getMaUser() {
        return this.maUser;
    }

    public void setMaUser(String maUser) {
        this.maUser = maUser;
    }

    @Column(name = "HOTEN", length = 50)
    public String getHoten() {
        return this.hoten;
    }

    public void setHoten(String hoten) {
        this.hoten = hoten;
    }

    @Column(name = "MA_CN", length = 4)
    public String getMaCn() {
        return this.maCn;
    }

    public void setMaCn(String maCn) {
        this.maCn = maCn;
    }

    @Column(name = "TEN_CN", length = 100)
    public String getTenCn() {
        return this.tenCn;
    }

    public void setTenCn(String tenCn) {
        this.tenCn = tenCn;
    }

    @Column(name = "GROUP_USER", precision = 2, scale = 0)
    public Byte getGroupUser() {
        return this.groupUser;
    }

    public void setGroupUser(Byte groupUser) {
        this.groupUser = groupUser;
    }

    @Column(name = "LANDANGNHAP", precision = 2, scale = 0)
    public Byte getLanDangNhap() {
        return this.landangnhap;
    }

    public void setLanDangNhap(Byte landangnhap) {
        this.landangnhap = landangnhap;
    }

    @Column(name = "PASSWORD", length = 8)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String pass) {
        this.password = pass;
    }

    @Column(name = "LANDANGNHAPSAI", precision = 1, scale = 0)
    public Byte getLanDangNhapSai() {
        return this.landangnhapsai;
    }

    public void setLanDangNhapSai(Byte landangnhapsai) {
        this.landangnhapsai = landangnhapsai;
    }

    @Column(name = "TINHTRANG", precision = 1, scale = 0)
    public Byte getTinhTrang() {
        return this.tinhtrang;
    }

    public void setTinhTrang(Byte tinhtrang) {
        this.tinhtrang = tinhtrang;
    }

    @Column(name = "EMAIL", length = 50)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
